v= int(input('Digite um numero para ver sua tabuada: '))
print('=============')
print('{} X {} = {}'.format(1,v,v*1))
print('{} X {} = {}'.format(2,v,v*2))
print('{} X {} = {}'.format(3,v,v*3))
print('{} X {} = {}'.format(4,v,v*4))
print('{} X {} = {}'.format(5,v,v*5))
print('{} X {} = {}'.format(6,v,v*6))
print('{} X {} = {}'.format(7,v,v*7))
print('{} X {} = {}'.format(8,v,v*8))
print('{} X {} = {}'.format(9,v,v*9))
print('{} X {} = {}'.format(10,v,v*10))
print('{} X {} = {}'.format(11,v,v*11))
print('{} X {} = {}'.format(12,v,v*12))
print('=============')
